spring:
  application:
    name: mcp-remote-client#local
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: "qwen2.5:7b"
        options:
          temperature: 0
    mcp:
      client:
        #        stdio:
        #          servers-configuration: classpath:mcp-servers.json
        sse:
          connections:
            mcp-client:
              url: http://localhost:8081

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
    org.springframework.ai.mcp: DEBUG  # Enable MCP client debugging
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"

