# noinspection SpellCheckingInspection
spring:
  application:
    name: ai-app#local
  docker:
    compose:
      stop:
        command: down
  ai:
    vectorstore:
      qdrant:
        initialize-schema: true
        host: localhost
        port: 6334
        collection-name: rag
    model:
      chat: ollama
    ollama:
      chat:
        model: llama3.2
        options:
          temperature: 0
          top-k: 1
          top-p: 1
          repeat-penalty: 1
          seed: 42
server:
  port: 8080
logging:
  level:
    org:
      springframework:
        ai: DEBUG

